name: Lint

on:
  pull_request_target:
    branches: [junk/prettier/main]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Update source code
        run: eslint "index.js" --fix

      - name: Prettify code
        uses: creyD/prettier_action@v3.1
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write index.js
          commit_message: "Format code with prettier"
          only_changed: true
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Linter - GitHub Actions
          author_email: linter@github.com
          message: "Lint code with eslint and prettier"
          add: "index.js"
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GH_TOKEN }}
